Areas/Admin/Controllers/QuanlysachController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using DoAnPTTKHDT.Models;
using PagedList.Mvc;
using PagedList;

namespace DoAnPTTKHDT.Areas.Admin.Controllers
{
    public class QuanlysachController : Controller
    {
        private WebsiteBanSachEntities db = new WebsiteBanSachEntities();

        // GET: Admin/Quanlysach
        public ActionResult Index(int? page)
        {
            int iSize = 4;
            int iPageNum = (page ?? 1);
            var sach = from s in db.SACH select s;
            return View(sach.OrderBy(s => s.MaSach).AsEnumerable().ToPagedList(iPageNum, iSize));
        }

        // GET: Admin/Quanlysach/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SACH sACH = db.SACH.Find(id);
            if (sACH == null)
            {
                return HttpNotFound();
            }
            return View(sACH);
        }

        // GET: Admin/Quanlysach/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.MaCD = new SelectList(db.CHUDE.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NHAXUATBAN.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(SACH sach, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            // Đưa dữ liệu vào DropDown
            ViewBag.MaCD = new SelectList(db.CHUDE.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NHAXUATBAN.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            if (fFileUpload == null)
            {
                // Nội dung thông báo yêu cầu chọn ảnh bìa
                ViewBag.ThongBao = " Hãy chọn ảnh bìa . ";
                // Lưu thông tin để khi load lại trang do yêu cầu chọn ảnh bìa sẽ hiển thị               các thông tin này lên trang
                ViewBag.TenSach = f["sTenSach"];
                ViewBag.MoTa = f["sMoTa"];
                ViewBag.SoLuong = int.Parse(f["iSoLuong"]);
                ViewBag.GiaBan = decimal.Parse(f["mGiaBan"]);
                ViewBag.MaCD = new SelectList(db.CHUDE.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe", int.Parse(f["MaCD"]));
                ViewBag.MaNXB = new SelectList(db.NHAXUATBAN.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", int.Parse(f["MaNXB"]));
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    // Lấy tên file ( Khai báo thư viện : System.IO )
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    // Lấy đường dẫn lưu file
                    var path = Path.Combine(Server.MapPath("~/Content/Images"), sFileName);
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    // Lưu Sạch vào CSDL
                    sach.TenSach = f["sTenSach"];
                    sach.MoTa = f["sMoTa"].Replace("<p>", " ").Replace("</p> ", "\n");
                    sach.HinhMinhHoa = sFileName;
                    sach.NgayCapNhat = Convert.ToDateTime(f["dNgayCapNhat"]);
                    sach.SoLuongBan = int.Parse(f["iSoLuong"]);
                    sach.DonGia = decimal.Parse(f["mGiaBan"]);
                    sach.MaCD = int.Parse(f["MaCD"]);
                    sach.MaNXB = int.Parse(f["MaNXB"]);
                    db.SACH.Add(sach);
                    db.SaveChanges();
                    // Về lại trang Quản lý sách
                    return RedirectToAction("Index");
                }
                return View();
            }
        }
        // GET: Admin/Quanlysach/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var sach = db.SACH.SingleOrDefault(n => n.MaSach == id);
            if (sach == null)

            {
                Response.StatusCode = 404;
                return null;
            }
            // Hiển thị danh sách chủ đề và nhà xuất bản đồng thời chọn chủ đề và nhà xuất bản của cuốn hiện tại
            ViewBag.MaCD = new SelectList(db.CHUDE.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe", sach.MaCD);
            ViewBag.MaNXB = new SelectList(db.NHAXUATBAN.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            return View(sach);
        }


        [HttpPost]
        [ValidateInput(false)]

        public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
        {

            var sach = db.SACH.AsEnumerable().SingleOrDefault(n => n.MaSach == int.Parse(f["iMaSach"]));
            ViewBag.MaCD = new SelectList(db.CHUDE.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe", sach.MaCD);

            ViewBag.MaNXB = new SelectList(db.NHAXUATBAN.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);

            if (ModelState.IsValid)

            {
                if (fFileUpload != null)
                {

                    //Lay tén file (Khai bao thu vién: System.10)
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Images"), sFileName);
                    //Kiém tra file da ton tai chua
                    if (!System.IO.File.Exists(path))
                    {

                        fFileUpload.SaveAs(path);
                    }
                    sach.HinhMinhHoa = sFileName;
                }
                //Lutu Sach vao CSDL
                sach.TenSach = f["sTenSach"];
                sach.MoTa = f["sMoTa"].Replace("<p>", "").Replace("</p>", "\n");
                sach.NgayCapNhat = Convert.ToDateTime(f["dNgayCapNhat"]);
                sach.SoLuongBan = int.Parse(f["isoLuong"]);
                sach.DonGia = decimal.Parse(f["mGiaBan"]);
                sach.MaCD = int.Parse(f["MaCD"]);
                sach.MaNXB = int.Parse(f["MaNxB"]);
                db.SaveChanges();
                //N@ igi trang Quan ly s
                return RedirectToAction("Index");
            }
            return View(sach);
        }


        // GET: Admin/Quanlysach/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SACH sACH = db.SACH.Find(id);
            if (sACH == null)
            {
                return HttpNotFound();
            }
            return View(sACH);
        }

        // POST: Admin/Quanlysach/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SACH sACH = db.SACH.Find(id);
            db.SACH.Remove(sACH);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Quanlysach/Create.cshtml
@model DoAnPTTKHDT.Models.SACH
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <section class="content">
        <div class="container">
            <h2 style="text-align:center;">THÊM MỚI SÁCH</h2>

            @*Thêm thuộc tính cho form để upload ảnh *@
            @using (Html.BeginForm("Create", "Quanlysach", FormMethod.Post, new { @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">

                        <label class="control-label col-md-2">Tên sách:</label>
                        <div class="col-md-10">
                            <input type="text" size="70" name="sTenSach" value="@ViewBag.TenSach" required />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Mô tả:</label>
                        <div class="col-md-10">
                            <textarea id="mytextarea" name="sMoTa">@ViewBag.MoTa</textarea>
                            <script src="https://cdn.tiny.cloud/1/rvt1c4e3h6r9h3z9d9rhddwydcn9o15cvz3keb7nt1b10mob/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

                            <script>
                                tinymce.init({
                                    selector: '#mytextarea'
                                });
                            </script>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Ảnh bìa:</label>
                        <div class="col-md-10">
                            <input type="file" name="fFileUpload" />
                            @*Thông báo lỗi yêu cầu phải chọn ảnh bìa*@
                            @ViewBag.ThongBao
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Ngày cập nhật:</label>
                        <div class="col-md-10">
                            <input type="date" name="dNgayCapNhat" required />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Số lượng:</label>
                        <div class="col-md-10">
                            <input type="number" min="1" required name="iSoLuong" value="@ViewBag.SoLuong" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Giá bán:</label>
                        <div class="col-md-10">
                            <input type="number" min="1" required name="mGiaBan" value="@ViewBag.GiaBan" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Chủ đề:</label>
                        <div class="col-md-10">
                            @*Hiển thị ViewBag.MaCD vào dropdownlist*@
                            @Html.DropDownList("MaCD")
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Nhà xuất bản:</label>
                        <div class="col-md-10">
                            @Html.DropDownList("MaNXB")
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Thêm mới" class="btn btn-success" />
                            @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-success" })
                        </div>
                    </div>
                </div>
            }
          
        </div>
    </section>
</div>

Areas/Admin/Views/Quanlysach/Delete.cshtml
@model DoAnPTTKHDT.Models.SACH

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <section class="content">
        <div class="container">
            <h2 style="text-align:center;">Bạn muốn xóa sách này?</h2>
            <div>

                <hr />
                <dl>
                <dt>
                    Tên sách:
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.TenSach)
                </dd>
                <dt>
                    Mô tả:
                </dt>
                <dd>
                    @Html.Raw(@Model.MoTa.ToString().Replace("\n", "</p><p>"))
                </dd>
                <dt>
                    Ảnh bìa:
                </dt>
                <dd>
                    <img src="~/Content/Images/@Model.HinhMinhHoa" alt=" @Model.TenSach">
                </dd>
                <dt>
                    Ngày cập nhật:
                </dt>
                <dd>
                    @Html.FormatValue(@Model.NgayCapNhat, "{0:dd/MM/yyyy}")
                </dd>
                <dt>
                    Số lượng bán:
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.SoLuongBan)

                </dd>
                <dt>
                    Giá bán:
                </dt>
                <dd>
                    @Html.FormatValue(@Model.DonGia, "{0:#,##0}") VNĐ
                </dd>
                <dt>
                    Chủ đề:
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CHUDE.TenChuDe)
                </dd>
                <dt>
                    Nhà xuất bản:
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.NHAXUATBAN.TenNXB)
                </dd>
                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Xóa" class="btn btn-danger" /> 
                @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-success" })
            </div>
                }
            </div>
        </div>
    </section>
</div>

Areas/Admin/Views/Quanlysach/Details.cshtml
@model DoAnPTTKHDT.Models.SACH

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <section class="content">
        <div class="container">
            <h2 style="text-align:center;">CHI TIẾT SÁCH</h2>

        
            <style type="text/css">
                img {
                    width: 200px;
                    margin-bottom: 20px;
                }
            </style>

            <div>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Tên sách:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TenSach)
                    </dd>
                    <dt>
                        Mô tả:
                    </dt>
                    <dd>
                        @Html.Raw(@Model.MoTa.ToString().Replace("\n", "</p><p>"))
                    </dd>
                    <dt>
                        Ảnh bìa:
                    </dt>
                    <dd>
                        <img src="~/Content/Images/@Model.HinhMinhHoa" alt=" @Model.TenSach">
                    </dd>
                    <dt>
                        Ngày cập nhật:
                    </dt>
                    <dd>
                        @Html.FormatValue(@Model.NgayCapNhat, "{0:dd/MM/yyyy}")
                    </dd>
                    <dt>
                        Số lượng bán:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.SoLuongBan)

                    </dd>
                    <dt>
                        Giá bán:
                    </dt>
                    <dd>
                        @Html.FormatValue(@Model.DonGia, "{0:#,##0}") VNĐ
                    </dd>
                    <dt>
                        Chủ đề:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CHUDE.TenChuDe)
                    </dd>
                    <dt>
                        Nhà xuất bản:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.NHAXUATBAN.TenNXB)
                    </dd>
                </dl>
            </div>
            <p>
                <a href="@Url.Action("Edit", new { id = Model.MaSach })" class="btn btn-warning" role="button">Sửa</a>
                @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-success" })
            </p>

        </div>
    </section>
</div>

Areas/Admin/Views/Quanlysach/Edit.cshtml
@model DoAnPTTKHDT.Models.SACH
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <section class="content">
        <div class="container">

            <h2> ĐIỀU CHỈNH THÔNG TIN SÁCH</h2>
            @*Thêm thuộc tính cho form để upload ảnh *@
            @using (Html.BeginForm("Edit", "Quanlysach", FormMethod.Post, new { @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <label class="control-label col-md-2">Mã sách:</label>
                        <div class="col-md-10">
                            @*Chỉ hiển thị mã sách không cho sửa*@
                            <input type="text" size="70" name="iMaSach" value="@Model.MaSach" readonly />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Tên sách:</label>
                        <div class="col-md-10">
                            <input type="text" size="70" name="sTenSach" value="@Model.TenSach" required />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Mô tả:</label>
                        <div class="col-md-10">
                            <textarea id="mytextarea" name="sMoTa">
                            <p>@Model.MoTa.Replace("\n", "</p><p>")</p> 
             </textarea>
                            <script src="https://cdn.tiny.cloud/1/rvt1c4e3h6r9h3z9d9rhddwydcn9o15cvz3keb7nt1b10mob/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

                            <script>
                                tinymce.init({
                                    selector: '#mytextarea'
                                });
                            </script>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Ảnh bìa:</label>
                        <div class="col-md-10">
                            <input type="file" name="fFileUpload" />
                        </div>
                            <img src="~/Content/Images/@Model.HinhMinhHoa" width="120"> (Ảnh hiện tại)
                    </div>


                    <div class="form-group">
                        <label class="control-label col-md-2">Ngày cập nhật:</label>
                        <div class="col-md-10">
                            <input type="datetime" name="dNgayCapNhat" required value="@Convert.ToDateTime(Model.NgayCapNhat)" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Số lượng:</label>
                        <div class="col-md-10">
                            <input type="number" min="1" required name="iSoLuong" value="@Model.SoLuongBan" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Giá bán:</label>
                        <div class="col-md-10">
                            <input type="number" min="1" required name="mGiaBan" value="@Model.DonGia" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Chủ đề:</label>
                        <div class="col-md-10">
                            @Html.DropDownList("MaCD")
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Nhà xuất bản:</label>
                        <div class="col-md-10">
                            @Html.DropDownList("MaNXB")
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="LƯU THÔNG TIN" class="btn btn-success" />
                            @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-success" })
                        </div>
                    </div>
                </div>

            }


            <div>  </div>

        </div>
    </section>
</div>

Areas/Admin/Views/Quanlysach/Index.cshtml
@using DoAnPTTKHDT.Models
@using PagedList.Mvc
@model PagedList.PagedList<DoAnPTTKHDT.Models.SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="content-wrapper">
    <section class="content">
        <div class="container">
            <h2 style="text-align:center;">QUẢN LÝ SÁCH</h2>
            <p>
                @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-primary" })
            </p>

            @helper  Truncate(string s, int length)
            {
                if (s.Length < length)
                {
                    @s
                }
                else
                {
                    @s.Substring(0, length)<text>...</text>
                }
            }




            <table class="table">
                <tr>
                    <th style="text-align:center;width:140px"> Tên sách</th>
                    <th style="text-align:center;width:200px">
                        Mô tả
                    </th>
                    <th style="text-align:center;width:80px">
                        Hình ảnh
                    </th>
                    <th style="text-align:center;width:100px">
                        Ngày cập nhật
                    </th>
                    <th style="text-align:center;width:80px">
                        Số lượng
                    </th>
                    <th style="text-align:center;width:80px">
                      Giá
                    </th>
                    <th style="text-align:center;width:100px">
                        Chủ đề
                    </th>
                    <th style="text-align:center;width:100px">
                        Nhà xuất bản
                    </th>
                    <th style="text-align:center">

                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Truncate(item.TenSach, 50)
                        </td>
                        <td>
                            @Html.Raw(Truncate(item.MoTa, 70).ToString())
                        </td>
                        <td>
                            <img src="~/Content/Images/@item.HinhMinhHoa" style="width:100px;" />
                        </td>
                        <td>
                            @Html.FormatValue(@item.NgayCapNhat, "{0:dd/MM/yyyy}")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoLuongBan)
                        </td>
                        <td>
                            @Html.FormatValue(item.DonGia, "{0:#,##0}")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CHUDE.TenChuDe)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NHAXUATBAN.TenNXB)
                        </td>

                        <td>
                            <a href="@Url.Action("Edit", new { id = item.MaSach })" class="btn btn-warning" role="button">Sửa</a>


                        </td>
                        <td>
                            <a href="@Url.Action("Details",new {id=item.MaSach})" class="btn btn-success" role="button">Xem</a>

                        </td>
                        <td>

                            <a href="@Url.Action("Delete", new { id = item.MaSach })" class="btn btn-danger" role="button">Xóa</a>
                        </td>
                    </tr>
                }
            </table>
            <div style="text-align:right;">
            Trang @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
            </div>

            <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
            </div>

        <style>
            .MenuTrang {
                display: inline;
                text-align: center;
            }
        </style>
        </div>
    </section>
</div>